import { POLICY_EN } from './content/privacy-policy';
import { TERMS_EN } from './content/terms-of-use';
import { MIN_ORDER_LIMIT } from '../helpers';

export default {
  RIGHTS_RESERVED: 'All Rights Reserved. Design By Gazar.am',
  HOME: 'Home',
  TITLE: 'Fruit and vegetable delivery service | gazar.am',
  SHOP: 'Shop',
  ABOUT_US: 'About Us',
  MENU: 'Menu',
  LOGIN: 'Log In',
  REGISTRATION: 'Registration',
  MY_ACCOUNT: 'My Account',
  MY_WISHES: 'My Wishlist',
  ALL: 'All',
  FRUITS: 'Fruits',
  VEGETABLE: 'Vegetable',
  ORGANIC: 'Organic',
  CATEGORIES: 'Categories',
  BASKET: 'Basket',
  CUSTOMER: 'Customer',
  TOP_RATED: 'Top Rated',
  SEARCH: 'Search',
  APPLE: 'Apple',
  AMD: 'AMD',
  ADD: 'Add',
  UPDATE_IN_BASKET: 'Update in basket',
  KG: 'Kg',
  ITEM: 'Item',
  LITRE: 'Litre',
  ADDRESS: 'Address',
  SHIPPING_ADDRESS: 'Shipping Address',
  PRODUCT: 'Product',
  PRODUCT_TYPE: 'Product Type',
  PRICE: 'Price',
  QUANTITY: 'Quantity',
  TOTAL_PRICE: 'Total Price',
  CANCEL: 'Cancel',
  FOLLOW_US: 'Follow us on : ',
  CUSTOMER_LOGIN: 'Customer Login',
  LOGIN_WITH_PHONE_NUMBER: 'Login with phone number',
  LOGIN_WITH_PASSWORD: 'Login with password',
  CUSTOMER_REGISTRATION: 'Customer Registration',
  PHONE_NUMBER: 'Phone Number',
  REMEMBER_ME: 'Remember me',
  VERIFY: 'Verify',
  FORGOT_PASSWORD: 'Forgot Password',
  GET_RESET_LINK: 'Get reset link',
  RESET_LINK_SENT: 'If we have your email, then we already sent you password reset link.',
  BY_SIGN_IN: 'By signing in you are accepting our',
  TERMS: 'Terms of use',
  VERIFICATION_CODE: 'Verification Code',
  UNABLE_TO_SEND_SMS: 'Could not send message to mentioned phone number',
  INVALID_CODE_NUMBER: 'Verification code is incorrect',
  CODE: 'Code',
  REGARDS: 'Regards Gazar.am',
  FREE_DELIVERY: 'Free Delivery',
  '10-11am': 'From 10am To 11am',
  '10-11am-DESCRIPTION': 'Fresh morning',
  '13-14pm': 'From 1pm To 2pm',
  '13-14pm-DESCRIPTION': 'Healthy break',
  '16-17pm': 'From 4pm To 5pm',
  '16-17pm-DESCRIPTION': 'Half day refresh',
  '19-20pm': 'From 7pm To 8pm',
  '19-20pm-DESCRIPTION': 'Vitamine recharge',
  TOP_SELLING_PRODUCTS: 'Most favorite products',
  ALWAYS_FRESH_SLIDER: 'Always fresh and selective products',
  SHOW_MORE: 'Show more products',
  SHOP_PRODUCTS: 'Products',
  ORDER_DETAILS: 'Order Details',
  NEXT: 'Next',
  ORDER: 'Order',
  ORDER_NOTES: 'Order Notes',
  PRODUCT_COUNT: 'Products Count',
  DELIVERY_TIME: 'Delivery Time',
  CLEAR: 'Clear',
  ACCOUNT_INFORMATION: 'Account Information',
  PROFILE: 'Profile',
  MY_ORDERS: 'My Orders',
  ORDER_AGAIN: 'Order again',
  EDIT: 'Edit',
  SAVE: 'Save',
  FIRST_NAME: 'First name',
  LAST_NAME: 'Last name',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  REPEATED_PASSWORD: 'Repeat password',
  NAME: 'Name',
  MY_ADDRESSES: 'My addresses',
  DONT_HAVE_ADDRESSES: "You don't have saved addresses yet",
  CONTACT_US: 'Contact us',
  BUSINESS_HOURS: 'Business hours',
  MONDAY: 'Monday',
  FRIDAY: 'Friday',
  LOGIN_DESCRIPTION: "If you don't have account yet, system will automatically register you on first login",
  TRY_AGAIN_IF_NO_SMS: "If you haven't received SMS in 2 minutes, please try again.",
  ADDRESS_IS_REQUIRED: 'Address field is required',
  ACCOUNT_INFO_FIELDS_REQUIRED: 'First name, last name and phone number are required fields',
  REMOVE: 'Remove',
  ARE_YOU_SURE_REMOVE_ADDRESS: 'Are you sure, you want to remove this address?',
  LOGOUT: 'Logout',
  DONT_HAVE_ORDERS: "You don't have orders yet",
  MANAGE_ACCOUNT_ADDRESSES: 'Add or remove addresses',
  CLEAR_BASKET: 'Clear Basket',
  INVALID_PRODUCTS_LIST: 'Unhandled issue with products information, please try again later',
  INVALID_DELIVERY_TIME: 'Wrong delivery time',
  INVALID_ADDRESS: 'Address is invalid',
  ORDER_SENT: 'Your order completed',
  ORDER_SUCCESS: 'Thank you for your order. Soon you will receive a message with order details, our specialist will contact you if necessary.',
  GO_TO_SHOP: 'Go to shopping',
  SURE_TO_REMOVE_PRODUCT_FROM_BASKET: 'Are you sure you want to remove product from basket?',
  MIN_ORDER_PRICE: 'Minimum basket price',
  MIN_ORDER_PRICE_ERROR: `Minimum basket price ${MIN_ORDER_LIMIT}AMD`,
  MIN_ORDER_PRICE_INFO: `Total basket price should be more than ${MIN_ORDER_LIMIT}AMD to set an order. Please choose more products or change quantity of existing ones.`,
  CLOSE: 'Close',
  TOMORROW: 'Tomorrow',
  TODAY: 'Today',
  ORDER_THIS_BASKET: 'Order this basket',
  SHARE_WITH_FRIENDS: 'Share with friends',
  SHARE_CAPTION_TEXT: 'Made an order from gazar.am website 🎉 look what I ordered...',
  BONUS: 'Bonus',
  POINTS: 'Points',
  'GAZARAM-ADDRESS': '49 Pushkin St, Yerevan 0002, Armenia',
  TERMS_OF_USE: 'Terms of use',
  PRIVACY_POLICY: 'Privacy policy',
  ORDER_AND_DELIVERY: 'Ordering and Delivery',
  PRIVACY_POLICY_DOCUMENT: POLICY_EN,
  TERMS_OF_USE_DOCUMENT: TERMS_EN,
  OFTEN_ORDERED_WITH: 'Often ordered with',
  WILL_DO_LATER: 'Remind me later',
  ACCOUNT_INFO_MODAL_TEXT: "You have been using our service, but we don't know your name 🤔",
  FEATURED_PRODUCTS: 'Featured products',
  RESEND_CODE: 'Resend code',
  ORDER_DATE: 'Order date',
  PAYMENT_CODE: 'Payment Code',
  PAYMENT_AMOUNT: 'Payment Amount',
  PAYMENT_STATUS: 'Payment Status',
  PAYMENT_SUCCESS: 'Paid',
  PAYMENT_DECLINED: 'Declined from bank',
  PAYMENT_METHOD: 'Payment method',
  CASH_PAYMENT: 'Cash',
  ONLINE_PAYMENT: 'Credit Card',
  IDRAM_PAYMENT: 'Idram',
  INVALID_EMAIL_OR_PASSWORD: 'Invalid email or password.',
  USER_ALREADY_EXISTS: 'User with this email or phone number already exists. Try resetting password.',
  PASSWORD_NOT_SECURE: 'Password should be more than 6 symbols',
  PASSWORD_IS_NOT_THE_SAME: 'Passwords are not the same',
  REGISTRATION_EMAIL_SENT: 'Thank you for joining Gazar.am family! Please check your email to complete registration.',
  INVALID_PHONE_NUMBER: 'Given Phone number is invalid.',
  DELIVERY_DAY: 'Delivery Date',
  FAILED_PAYMENT: 'Faild Payment',
  ORDER_NOW:"Order now"
};